### ISSUE TITLE
Cannot create a valid smp file for the hachette_green

### ISSUE THREAD

**Issue by Rix565** [oyooyo/audiocube#10]
When i want to make a smp file from a mp3 file, i only get some beeps boops.
Here is the command I used:
```
python audiocube.py hachette_green encrypt song.mp3
```
It given me a song.smp file (I renamed it T1036 to match to my figurine), and it only does some beeps boops when i plug the microsd card with the patched files on it.
I retried multiples times without any changes.
My hachette_green region: French
Thanks!

**Comment by Rix565** [comment]
found solution.
need to replace header of mp3 file

**Comment by oyooyo** [comment]
@Rix565 sorry, I somehow forgot to reply to your initial posting.

I'm glad you figured out how fix the problem. Can you tell what the problem was exactly?

**Comment by Rix565** [comment]
Well, it wasn't playing the mp3 converted file at all.
It was doing some sort of audible error code (the beeps boops I was talking about)
I just needed to replace the mp3 original file header with the header of the mp3 converted original .smp file I wanted to replace.
