### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by pokryva** [oyooyo/audiocube#4]
Hi,
Is it just me or the docs links seem to be broken? In order to be able to see the readme in it's full glory I need to go through repo, e.g. audiocube > docs > devices > hachette > index.md. If I try to get there from mail page readme.md - it's all 404s

**Comment by oyooyo** [comment]
Thank you for pointing this out. I just fixed a few broken links I immediately realized, but there might be more, so if you still find some, please tell me.

**Comment by pokryva** [comment]
So far so good! Thanks!
